# Poetry pyproject.toml: https://python-poetry.org/docs/pyproject/
[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "test-python-project"
version = "0.1.0"
description = "Description for `test-python-project`"
readme = "README.md"
authors = ["a1d4r <a1d4r@example.com>"]
repository = "https://github.com/a1d4r/test-python-project"
homepage = "https://github.com/a1d4r/test-python-project"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.2.1"
bandit = "^1.7.5"
black = "^23.9.1"
darglint = "^1.8.1"
isort = {extras = ["colors"], version = "^5.12.0"}
mypy = "^1.5.1"
mypy-extensions = "^1.0.0"
pre-commit = "^3.4.0"
pydocstyle = "^6.3.0"
pylint = "^2.17.5"
pytest = "^7.4.2"
pyupgrade = "^3.10.1"
safety = "^2.3.5"
pytest-html = "^4.0.2"
pytest-cov = "^4.1.0"
types-setuptools = "^68.2.0.0"

[tool.black]
# https://github.com/psf/black
target-version = ["py39"]
line-length = 88
color = true

exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | env
    | venv
)/
'''

[tool.isort]
# https://pycqa.github.io/isort/docs/configuration/config_files.html
py_version = "39"
line_length = 88

known_typing = ["typing", "types", "typing_extensions", "mypy", "mypy_extensions"]
sections = ["FUTURE", "TYPING", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
include_trailing_comma = true
profile = "black"
multi_line_output = 3
indent = 4
color_output = true

[tool.mypy]
# https://mypy.readthedocs.io/en/latest/config_file.html#using-a-pyproject-toml-file
python_version = "3.9"
pretty = true
show_traceback = true
color_output = true
#plugins = [
#  "pydantic.mypy"
#]

allow_redefinition = false
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
implicit_reexport = false
no_implicit_optional = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false

#[tool.pydantic-mypy]
## https://pydantic-docs.helpmanual.io/mypy_plugin/#configuring-the-plugin
#init_forbid_extra = true
#init_typed = true
#warn_required_dynamic_aliases = true

[tool.pytest.ini_options]
# https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml
# Directories that are not visited by pytest collector:
norecursedirs = ["hooks", "*.egg", ".eggs", "dist", "build", "docs", ".tox", ".git", "__pycache__"]
doctest_optionflags = ["NUMBER", "NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL"]

# Extra options:
addopts = [
  "--strict-markers",
  "--tb=short",
  "--doctest-modules",
  "--doctest-continue-on-failure",
]

[tool.coverage.run]
source = ["tests"]

[coverage.paths]
source = "app"

[coverage.run]
branch = true

[coverage.report]
fail_under = 50
show_missing = true

[tool.pylint.master]
fail-under = 10.0
ignore = ["CVS"]

[tool.pylint.messages_control]
max-line-length = 88
extension-pkg-whitelist = ["pydantic"]
disable = [
  "missing-docstring",
  "unused-argument",
  "no-value-for-parameter",
  "no-member",
  "no-else-return",
  "line-too-long",
  "fixme",
  "protected-access",
  "too-few-public-methods",
  "invalid-name",
  "unspecified-encoding",
  "redefined-outer-name",  # pytest fixtures
]

[tool.pylint.refactoring]
max-nested-blocks = 3

[tool.pylint.miscellaneous]
notes = ["FIXME", "TODO"]

[tool.pylint.basic]
class-attribute-naming-style = "any"
class-const-naming-style = "any"
good-names=["i", "j", "k", "e", "x", "id", "_", "pk"]

[tool.pylint.format]
max-module-lines = 300

[tool.pylint.similarities]
min-similarity-lines = 10
ignore-docstrings = true
ignore-comments = true
ignore-imports = true

[tool.pylint.design]
max-args = 10
max-attributes = 10
max-statements = 30

[tool.pylint.exceptions]
overgeneral-exceptions = ["builtins.BaseException", "builtins.Exception"]

[tool.bandit]
skips = ["B101"]
